### ISSUE TITLE
can't run inference

### ISSUE THREAD

**Issue by barinov274** [Sentdex/GANTheftAuto#11]
> max@pop-os:/media/max/Data1/GANTheftAuto$ ./scripts/gtav_inference_demo.sh
> Traceback (most recent call last):
>   File "/media/max/Data1/GANTheftAuto/inference.py", line 273, in <module>
>     inference(opts.gpu, opts)
>   File "/media/max/Data1/GANTheftAuto/inference.py", line 91, in inference
>     torch.cuda.set_device(gpu)
>   File "/home/max/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 264, in set_device
>     torch._C._cuda_setDevice(device)
>   File "/home/max/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
>     torch._C._cuda_init()
> RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
>

**Comment by daniel-kukiela** [comment]
Do you have Nvidia GPU in your system, with drivers installed and CUDA + cuDNN installed as well?
Please provide more information about your issue.

**Comment by barinov274** [comment]
I don't have it. I have Radeon RX 580 and openCL. Can I use OpenCL instead of Nvidia CUDA?

**Comment by daniel-kukiela** [comment]
Currently, ROCm is not supported. This is based on Nvidia's GameGAN and requires Nvidia's GPU.
Since we do not own any AMD GPUs, we are open for contribution to make it work.
