### ISSUE TITLE
Running inference issue

### ISSUE THREAD

**Issue by nookoyo** [Sentdex/GANTheftAuto#13]
Errors may have originated from an input operation.
Input Source operations connected to node model/spectral_normalization_1/conv2d_1/Conv2D:
 model/up_sampling2d/resize/ResizeNearestNeighbor (defined at \GANTheftAuto\upsample\upsample.py:17)

Not sure what the issue is, my GPU is a GTX 1070 & I have installed the latest drivers.

**Comment by daniel-kukiela** [comment]
I feel like you did not share an important part. Can you share the whole output to the console? As for now I'm not even sure what's the problem.

**Comment by nookoyo** [comment]
Traceback (most recent call last):
  File "C:\Users\User\GANTheftAuto\inference.py", line 273, in <module>
    inference(opts.gpu, opts)
  File "C:\Users\User\GANTheftAuto\inference.py", line 166, in inference
    upsampled_img = upsample.inference(np.rollaxis(prev_state[0].cpu().numpy(), 0, 3))
  File "C:\Users\User\GANTheftAuto\upsample\upsample.py", line 17, in inference
    upsampled = model.predict(np.expand_dims(img, axis=0))
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow\python\keras\engine\training.py", line 1727, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow\python\eager\def_function.py", line 956, in _call
    return self._concrete_stateful_fn._call_flat(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow\python\eager\function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow\python\eager\function.py", line 591, in call
    outputs = execute.execute(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node model/spectral_normalization_1/conv2d_1/Conv2D (defined at \AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow_addons\layers\spectral_normalization.py:100) ]] [Op:__inference_predict_function_3325]

Errors may have originated from an input operation.
Input Source operations connected to node model/spectral_normalization_1/conv2d_1/Conv2D:
 model/up_sampling2d/resize/ResizeNearestNeighbor (defined at \GANTheftAuto\upsample\upsample.py:17)

Function call stack:
predict_function

**Comment by daniel-kukiela** [comment]
Do you have an Nvidia GPU and CUDA + cuDNN installed? If yes, which versions?
